name: CI/CD - Documentación y Despliegue en Vercel

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest

    # No definimos env: aquí; la acción de Vercel leerá los Secrets directamente.

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # Paso 1: Instalar Node.js y dependencias
      - name: Configurar Node.js y Cachear
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          # Usamos cache: 'npm' esperando encontrar package-lock.json
          cache: "npm"

      - name: Instalar dependencias (incluyendo JSDoc)
        run: npm install

      - name: Debug - Verificar Path y NPM
        run: |
          echo "Current PATH: $PATH"
          which npm

      # ------------------------------------
      # 2. VERIFICACIÓN Y PRUEBAS (CI)
      # ------------------------------------

      # Requisito 1: Verificar que la página contiene JavaScript (script.js)
      - name: Verificar la presencia de código JS
        run: |
          if [ -f script.js ]; then
            echo "::notice file=script.js::El archivo script.js existe. Continuamos."
          else
            echo "::error file=script.js::Error: El proyecto requiere el archivo script.js."
            exit 1
          fi

      # Requisito 2: Ejecutar Pruebas Unitarias
      - name: Ejecutar Pruebas Unitarias
        run: npm test

      # ------------------------------------
      # 3. DOCUMENTACIÓN (Generación)
      # ------------------------------------

      # Requisito 3 & 4: Generar la documentación HTML con JSDoc
      - name: Generar la documentación (carpeta 'docs')
        # Esto ejecuta 'npm run docs' y crea la carpeta 'docs'
        run: npm run docs

      # ------------------------------------
      # 4. DESPLIEGUE (CD)
      # ------------------------------------

      # Requisito 5: Desplegar automáticamente en Vercel
      - name: Despliegue en Vercel (Solo carpeta DOCS)
        uses: amondnet/vercel-action@v25
        with:
          # ACCESO CORRECTO A LOS SECRETS: Siempre por su nombre
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          # ¡CRÍTICO! Apuntamos el despliegue a la carpeta 'docs' generada.
          working-directory: ./docs
